name: example
description: Example Project for flutter_chips_input

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_chips_input:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
